using Microsoft.VisualBasic;
using Newtonsoft.Json.Converters;
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Simpolo_Endpoint.Models
{
    public class ServiceResponse
    {
        public List<string> Errors { get; set; } = new List<string>();
        public List<string> Warnings { get; set; } = new List<string>();
        [JsonIgnore]
        public bool HasErrors { get { return Errors != null && Errors.Count > 0; } }
        [JsonIgnore]
        public bool HasWarnings { get { return Warnings != null && Warnings.Count > 0; } }

        public void addError(string error)
        {
            if (false == string.IsNullOrEmpty(error))
            {
                Errors.Add(error);
            }
        }

        public void addWarning(string warning)
        {
            if (false == string.IsNullOrEmpty(warning))
            {
                Warnings.Add(warning);
            }
        }

        public string GetErrors()
        {
            string result = null;

            if (Errors.Count > 0)
            {
                result = string.Join(Environment.NewLine, Errors);
            }

            return (result);
        }

        public string GetWarnings()
        {
            string result = null;

            if (Warnings.Count > 0)
            {
                result = string.Join(Environment.NewLine, Warnings);
            }

            return (result);
        }
    }

    public class Payload<T> : ServiceResponse
    {
        public T Result { get; set; }
        public string ResponseCode { get; set; } = "";
    }

    public class AuthResponce
    {
        public string UserInfo { get; set; }

        public string JsonToken { get; set; }

        public string Base64Image { get; set; }

        public string RefreshToken { get; set; }
        public string SessionID { get; set; }


    }
    public class AuthResponsePair
    {
        public AuthResponce AuthResponse1 { get; set; }
        public AuthResponce AuthResponse2 { get; set; }
    }














    //public class WMSCoreMessage : ServiceResponse
    //{
    //    private WMSCoreAuthentication _AuthToken;

    //    private EndpointConstants.DTO _Type;

    //    private object _EntityObject;

    //    private List<WMSExceptionMessage> _WMSMessages;

    //    public WMSCoreAuthentication AuthToken { get => _AuthToken; set => _AuthToken = value; }
    //    public EndpointConstants.DTO Type { get => _Type; set => _Type = value; }
    //    public object EntityObject { get => _EntityObject; set => _EntityObject = value; }
    //    public List<WMSExceptionMessage> WMSMessages { get => _WMSMessages; set => _WMSMessages = value; }

    //    public class WMSCoreAuthentication
    //    {
    //        private string _AuthKey;            // MAP CLIENT MAC
    //        private string _UserID;             // MAP WMS USER ID
    //        private string _AuthValue;          // MAP SESSION IDENTIFIER
    //        private int _RequestNumber;         // Request Sequence Number
    //        private string _LoginTimeStamp;   // MAP Login Timestamp, as Returned by SSO
    //        private string _AuthToken;          // MAP Auth Token Generated by WMS

    //        private int _SSOUSerID;          // MAP Inventrax SSO User ID
    //        private string _CookieIdentifier;   // MAP Cookie Identifier

    //        public string AuthKey { get => _AuthKey; set => _AuthKey = value; }
    //        public string UserID { get => _UserID; set => _UserID = value; }
    //        public string AuthValue { get => _AuthValue; set => _AuthValue = value; }
    //        public string LoginTimeStamp { get => _LoginTimeStamp; set => _LoginTimeStamp = value; }
    //        public string AuthToken { get => _AuthToken; set => _AuthToken = value; }
    //        public int RequestNumber { get => _RequestNumber; set => _RequestNumber = value; }
    //        public int SSOUSerID { get => _SSOUSerID; set => _SSOUSerID = value; }
    //        public string CookieIdentifier { get => _CookieIdentifier; set => _CookieIdentifier = value; }
    //    }

    //    public class WMSExceptionMessage : Exception
    //    {
    //        private string _WMSMessage;

    //        private string _WMSExceptionCode;

    //        private bool _ShowAsError;

    //        private bool _ShowAsWarning;

    //        private bool _ShowAsSuccess;

    //        private bool _ShowAsCriticalError;

    //        private bool _ShowUserConfirmDialogue;

    //        public string WMSMessage { get => _WMSMessage; set => _WMSMessage = value; }
    //        public string WMSExceptionCode { get => _WMSExceptionCode; set => _WMSExceptionCode = value; }
    //        public bool ShowAsError { get => _ShowAsError; set => _ShowAsError = value; }
    //        public bool ShowAsWarning { get => _ShowAsWarning; set => _ShowAsWarning = value; }
    //        public bool ShowAsSuccess { get => _ShowAsSuccess; set => _ShowAsSuccess = value; }
    //        public bool ShowAsCriticalError { get => _ShowAsCriticalError; set => _ShowAsCriticalError = value; }
    //        public bool ShowUserConfirmDialogue { get => _ShowUserConfirmDialogue; set => _ShowUserConfirmDialogue = value; }


    //    }

    //    public static class EndpointConstants
    //    {


    //        [JsonConverter(typeof(StringEnumConverter))]
    //        public enum DTO { None, LoginUserDTO, ProfileDTO, Inbound, Inventory, Exception, CycleCount, Outbound, DenestingDTO, PutAwayDTO, HouseKeepingDTO, POD, OutboundList, InboundList, POList, SOList, Tenant, Warehouse, Shipment, ScanDTO, InventoryDTO, APIInventoryDTO, MastersDTO, ReleaseOutbound, OutboundOrdersDTO, BulkOrderDTO, SupplierImportDTO, ItemMasterDTO, InboundDataDTO, SLOCToSLOCDTO, BinToBinDTO, SupplierReturnOBDDTO, CustomerReturnDTO, SupplierReturnDTO, UpdateItemMasterDTO, UpdateSupplierDTO, MiscReceipt, MiscIssue, CustomerImportDTO, SupplierCreationDTO, StockTakeDTO };
    //        [JsonConverter(typeof(StringEnumConverter))]
    //        public enum ScanType { Unloading, Putaway, Picking, Loading, DeNesting, Assortment };
    //        [JsonConverter(typeof(StringEnumConverter))]
    //        public enum LocationType { Bin, Dock, DeNesting, Staging, CrossDock, ExcessPicked, Quarantine };
    //    }

    //}

}